function getMoveNames() {
    const names = {
        '-': MoveIds.NONE,
        'Absorb': MoveIds.ABSORB,
        'Acid Armor': MoveIds.ACIDARMOR,
        'Acid': MoveIds.ACID,
        'Agility': MoveIds.AGILITY,
        'Amnesia': MoveIds.AMNESIA,
        'Aurora Beam': MoveIds.AURORABEAM,
        'Barrage': MoveIds.BARRAGE,
        'Barrier': MoveIds.BARRIER,
        'Bide': MoveIds.BIDE,
        'Bind': MoveIds.BIND,
        'Bite': MoveIds.BITE,
        'Blizzard': MoveIds.BLIZZARD,
        'Body Slam': MoveIds.BODYSLAM,
        'Bone Club': MoveIds.BONECLUB,
        'Bonemerang': MoveIds.BONEMERANG,
        'Bubble': MoveIds.BUBBLE,
        'Bubblebeam': MoveIds.BUBBLEBEAM,
        'Clamp': MoveIds.CLAMP,
        'Comet Punch': MoveIds.COMETPUNCH,
        'Confuse Ray': MoveIds.CONFUSERAY,
        'Confusion': MoveIds.CONFUSION,
        'Constrict': MoveIds.CONSTRICT,
        'Conversion': MoveIds.CONVERSION,
        'Counter': MoveIds.COUNTER,
        'Crabhammer': MoveIds.CRABHAMMER,
        'Cut': MoveIds.CUT,
        'Defense Curl': MoveIds.DEFENSECURL,
        'Dig': MoveIds.DIG,
        'Disable': MoveIds.DISABLE,
        'Dizzy Punch': MoveIds.DIZZYPUNCH,
        'Double Kick': MoveIds.DOUBLEKICK,
        'Double Team': MoveIds.DOUBLETEAM,
        'Double-Edge': MoveIds.DOUBLEEDGE,
        'Doubleslap': MoveIds.DOUBLESLAP,
        'Dragon Rage': MoveIds.DRAGONRAGE,
        'Dream Eater': MoveIds.DREAMEATER,
        'Drill Peck': MoveIds.DRILLPECK,
        'Earthquake': MoveIds.EARTHQUAKE,
        'Egg Bomb': MoveIds.EGGBOMB,
        'Ember': MoveIds.EMBER,
        'Explosion': MoveIds.EXPLOSION,
        'Fire Blast': MoveIds.FIREBLAST,
        'Fire Punch': MoveIds.FIREPUNCH,
        'Fire Spin': MoveIds.FIRESPIN,
        'Fissure': MoveIds.FISSURE,
        'Flamethrower': MoveIds.FLAMETHROWER,
        'Flash': MoveIds.FLASH,
        'Fly': MoveIds.FLY,
        'Focus Energy': MoveIds.FOCUSENERGY,
        'Fury Attack': MoveIds.FURYATTACK,
        'Fury Swipes': MoveIds.FURYSWIPES,
        'Glare': MoveIds.GLARE,
        'Growl': MoveIds.GROWL,
        'Growth': MoveIds.GROWTH,
        'Guillotine': MoveIds.GUILLOTINE,
        'Gust': MoveIds.GUST,
        'Harden': MoveIds.HARDEN,
        'Haze': MoveIds.HAZE,
        'Headbutt': MoveIds.HEADBUTT,
        'Hi Jump Kick': MoveIds.HIJUMPKICK,
        'Horn Attack': MoveIds.HORNATTACK,
        'Horn Drill': MoveIds.HORNDRILL,
        'Hydro Pump': MoveIds.HYDROPUMP,
        'Hyper Beam': MoveIds.HYPERBEAM,
        'Hyper Fang': MoveIds.HYPERFANG,
        'Hypnosis': MoveIds.HYPNOSIS,
        'Ice Beam': MoveIds.ICEBEAM,
        'Ice Punch': MoveIds.ICEPUNCH,
        'Jump Kick': MoveIds.JUMPKICK,
        'Karate Chop': MoveIds.KARATECHOP,
        'Kinesis': MoveIds.KINESIS,
        'Leech Life': MoveIds.LEECHLIFE,
        'Leech Seed': MoveIds.LEECHSEED,
        'Leer': MoveIds.LEER,
        'Lick': MoveIds.LICK,
        'Light Screen': MoveIds.LIGHTSCREEN,
        'Lovely Kiss': MoveIds.LOVELYKISS,
        'Low Kick': MoveIds.LOWKICK,
        'Meditate': MoveIds.MEDITATE,
        'Mega Drain': MoveIds.MEGADRAIN,
        'Mega Kick': MoveIds.MEGAKICK,
        'Mega Punch': MoveIds.MEGAPUNCH,
        'Metronome': MoveIds.METRONOME,
        'Mimic': MoveIds.MIMIC,
        'Minimize': MoveIds.MINIMIZE,
        'Mirror Move': MoveIds.MIRRORMOVE,
        'Mist': MoveIds.MIST,
        'Night Shade': MoveIds.NIGHTSHADE,
        'Pay Day': MoveIds.PAYDAY,
        'Peck': MoveIds.PECK,
        'Petal Dance': MoveIds.PETALDANCE,
        'Pin Missile': MoveIds.PINMISSILE,
        'Poison Gas': MoveIds.POISONGAS,
        'Poison Sting': MoveIds.POISONSTING,
        'Poisonpowder': MoveIds.POISONPOWDER,
        'Pound': MoveIds.POUND,
        'Psybeam': MoveIds.PSYBEAM,
        'Psychic': MoveIds.PSYCHIC,
        'Psywave': MoveIds.PSYWAVE,
        'Quick Attack': MoveIds.QUICKATTACK,
        'Rage': MoveIds.RAGE,
        'Razor Leaf': MoveIds.RAZORLEAF,
        'Razor Wind': MoveIds.RAZORWIND,
        'Recover': MoveIds.RECOVER,
        'Reflect': MoveIds.REFLECT,
        'Rest': MoveIds.REST,
        'Roar': MoveIds.ROAR,
        'Rock Slide': MoveIds.ROCKSLIDE,
        'Rock Throw': MoveIds.ROCKTHROW,
        'Rolling Kick': MoveIds.ROLLINGKICK,
        'Sand-Attack': MoveIds.SANDATTACK,
        'Scratch': MoveIds.SCRATCH,
        'Screech': MoveIds.SCREECH,
        'Seismic Toss': MoveIds.SEISMICTOSS,
        'Selfdestruct': MoveIds.SELFDESTRUCT,
        'Sharpen': MoveIds.SHARPEN,
        'Sing': MoveIds.SING,
        'Skull Bash': MoveIds.SKULLBASH,
        'Sky Attack': MoveIds.SKYATTACK,
        'Slam': MoveIds.SLAM,
        'Slash': MoveIds.SLASH,
        'Sleep Powder': MoveIds.SLEEPPOWDER,
        'Sludge': MoveIds.SLUDGE,
        'Smog': MoveIds.SMOG,
        'Smokescreen': MoveIds.SMOKESCREEN,
        'Softboiled': MoveIds.SOFTBOILED,
        'Solarbeam': MoveIds.SOLARBEAM,
        'Sonicboom': MoveIds.SONICBOOM,
        'Spike Cannon': MoveIds.SPIKECANNON,
        'Splash': MoveIds.SPLASH,
        'Spore': MoveIds.SPORE,
        'Stomp': MoveIds.STOMP,
        'Strength': MoveIds.STRENGTH,
        'String Shot': MoveIds.STRINGSHOT,
        'Struggle': MoveIds.STRUGGLE,
        'Stun Spore': MoveIds.STUNSPORE,
        'Submission': MoveIds.SUBMISSION,
        'Substitute': MoveIds.SUBSTITUTE,
        'Super Fang': MoveIds.SUPERFANG,
        'Supersonic': MoveIds.SUPERSONIC,
        'Surf': MoveIds.SURF,
        'Swift': MoveIds.SWIFT,
        'Swords Dance': MoveIds.SWORDSDANCE,
        'Tackle': MoveIds.TACKLE,
        'Tail Whip': MoveIds.TAILWHIP,
        'Take Down': MoveIds.TAKEDOWN,
        'Teleport': MoveIds.TELEPORT,
        'Thrash': MoveIds.THRASH,
        'Thunder Wave': MoveIds.THUNDERWAVE,
        'Thunder': MoveIds.THUNDER,
        'Thunderbolt': MoveIds.THUNDERBOLT,
        'Thunderpunch': MoveIds.THUNDERPUNCH,
        'Thundershock': MoveIds.THUNDERSHOCK,
        'Toxic': MoveIds.TOXIC,
        'Transform': MoveIds.TRANSFORM,
        'Tri Attack': MoveIds.TRIATTACK,
        'Twineedle': MoveIds.TWINEEDLE,
        'Vicegrip': MoveIds.VICEGRIP,
        'Vine Whip': MoveIds.VINEWHIP,
        'Water Gun': MoveIds.WATERGUN,
        'Waterfall': MoveIds.WATERFALL,
        'Whirlwind': MoveIds.WHIRLWIND,
        'Wing Attack': MoveIds.WINGATTACK,
        'Withdraw': MoveIds.WITHDRAW,
        'Wrap': MoveIds.WRAP,
    };
    return names;
}
